export default {
    sounds: {
      add: new AudioClip('sounds/addVoxel.mp3'),
      subtract: new AudioClip('sounds/subtractVoxel.mp3'),
      eyeDrop: new AudioClip('sounds/eyeDropVoxel.mp3')
    },
    models: {
        baseGrid: new GLTFShape('models/baseGrid.glb'),
        selector: new GLTFShape('models/selectorAlphaTexture.glb'),
        selectorNoCollider: new GLTFShape('models/selectorAlphaTextureNoCollider.glb'),
        anchorPoint: new GLTFShape('models/landUI/anchorPoint.gltf'),
        // uiBorder: new GLTFShape('models/landUI/ui_border.gltf'),
        // elevatorUiUp: new GLTFShape('models/landUI/elevatorUi_Up.gltf'),
        // elevatorUiDown: new GLTFShape('models/landUI/elevatorUi_Down.gltf'),
        // elevatorUpSelected: new GLTFShape('models/landUI/elevator_up_selected.gltf'),
        // elevatorDownSelected: new GLTFShape('models/landUI/elevator_down_selected.gltf'),
        // elevatorUpCollider: new GLTFShape('models/landUI/elevator_up_collider.gltf'),
        // elevatorDownCollider: new GLTFShape('models/landUI/elevator_down_collider.gltf'),
        // menu1Ui: new GLTFShape('models/landUI/menu1.gltf'),
        // menu1Selected: new GLTFShape('models/landUI/menu1_selected.gltf'),
        // menu1Collider: new GLTFShape('models/landUI/menu1_collider.gltf'),
        // menu2Ui: new GLTFShape('models/landUI/menu2.gltf'),
        // menu2Selected: new GLTFShape('models/landUI/menu2_selected.gltf'),
        // menu2Collider: new GLTFShape('models/landUI/menu2_collider.gltf'),
        // menu3Ui: new GLTFShape('models/landUI/menu3.gltf'),
        // menu3Selected: new GLTFShape('models/landUI/menu3_selected.gltf'),
        // menu3Collider: new GLTFShape('models/landUI/menu3_collider.gltf'),
        blankFloor: new GLTFShape('models/landUI/blankFloor.gltf'),
        wallUi: new GLTFShape('models/landUI/wallUi.gltf'),
        builderMenu: new GLTFShape('models/landUI/aetheriaBuilderMenu.gltf'),
        landRentalOptions: new GLTFShape('models/landUI/landRentalOptions.gltf'),
        btnRent1x1: new GLTFShape('models/landUI/btn_rent1x1.gltf'),
        btnRent2x1North: new GLTFShape('models/landUI/btn_rent2x1North.gltf'),
        btnRent2x1South: new GLTFShape('models/landUI/btn_rent2x1South.gltf'),
        btnRent2x1East: new GLTFShape('models/landUI/btn_rent2x1East.gltf'),
        btnRent2x1West: new GLTFShape('models/landUI/btn_rent2x1West.gltf'),
        btnRent2x2NorthEast: new GLTFShape('models/landUI/btn_rent2x2NorthEast.gltf'),
        btnRent2x2NorthWest: new GLTFShape('models/landUI/btn_rent2x2NorthWest.gltf'),
        btnRent2x2SouthEast: new GLTFShape('models/landUI/btn_rent2x2SouthEast.gltf'),
        btnRent2x2SouthWest: new GLTFShape('models/landUI/btn_rent2x2SouthWest.gltf'),
        selected_build: new GLTFShape('models/landUI/selected_build.gltf'),
        selected_market: new GLTFShape('models/landUI/selected_market.gltf'),
        marketBnt_collider: new GLTFShape('models/landUI/marketBnt_collider.gltf'),
        selected_rent: new GLTFShape('models/landUI/selected_rent.gltf'),
        selected_map: new GLTFShape('models/landUI/selected_map.gltf'),
        selected1x1Rent: new GLTFShape('models/landUI/selected_rent1x1.gltf'),
        selected2x1East: new GLTFShape('models/landUI/selected_rent2x1East.gltf'),
        selected2x1North: new GLTFShape('models/landUI/selected_rent2x1North.gltf'),
        selected2x1South: new GLTFShape('models/landUI/selected_rent2x1South.gltf'),
        selected2x1west: new GLTFShape('models/landUI/selected_rent2x1west.gltf'),
        selected2x2East: new GLTFShape('models/landUI/selected_rent2x2East.gltf'),
        selected2x2NorthEast: new GLTFShape('models/landUI/selected_rent2x2NorthEast.gltf'),
        selected2x2NorthWest: new GLTFShape('models/landUI/selected_rent2x2NorthWest.gltf'),
        selected2x2SouthEast: new GLTFShape('models/landUI/selected_rent2x2SouthEast.gltf'),
        selected2x2SouthWest: new GLTFShape('models/landUI/selected_rent2x2SouthWest.gltf'),
        colours: 
          {
            colour_1:  {
                  r1c1: new GLTFShape('models/c1/c1_r1c1.gltf'),
                  r1c2: new GLTFShape('models/c1/c1_r1c2.gltf'),
                  r1c3: new GLTFShape('models/c1/c1_r1c3.gltf'),
                  r1c4: new GLTFShape('models/c1/c1_r1c4.gltf'),
                  r1c5: new GLTFShape('models/c1/c1_r1c5.gltf'),
                  r1c6: new GLTFShape('models/c1/c1_r1c6.gltf'),
                  r2c1: new GLTFShape('models/c1/c1_r2c1.gltf'),
                  r2c2: new GLTFShape('models/c1/c1_r2c2.gltf'),
                  r2c3: new GLTFShape('models/c1/c1_r2c3.gltf'),
                  r2c4: new GLTFShape('models/c1/c1_r2c4.gltf'),
                  r2c5: new GLTFShape('models/c1/c1_r2c5.gltf'),
                  r2c6: new GLTFShape('models/c1/c1_r2c6.gltf'),
                  r2c7: new GLTFShape('models/c1/c1_r2c7.gltf'),
                  r3c1: new GLTFShape('models/c1/c1_r3c1.gltf'),
                  r3c2: new GLTFShape('models/c1/c1_r3c2.gltf'),
                  r3c3: new GLTFShape('models/c1/c1_r3c3.gltf'),
                  r3c4: new GLTFShape('models/c1/c1_r3c4.gltf'),
                  r3c5: new GLTFShape('models/c1/c1_r3c5.gltf'),
                  r3c6: new GLTFShape('models/c1/c1_r3c6.gltf'),
                  r3c7: new GLTFShape('models/c1/c1_r3c7.gltf'),
                  r3c8: new GLTFShape('models/c1/c1_r3c8.gltf'),
                  r4c1: new GLTFShape('models/c1/c1_r4c1.gltf'),
                  r4c2: new GLTFShape('models/c1/c1_r4c2.gltf'),
                  r4c3: new GLTFShape('models/c1/c1_r4c3.gltf'),
                  r4c4: new GLTFShape('models/c1/c1_r4c4.gltf'),
                  r5c1: new GLTFShape('models/c1/c1_r5c1.gltf'),
                  r5c2: new GLTFShape('models/c1/c1_r5c2.gltf'),
                  r5c3: new GLTFShape('models/c1/c1_r5c3.gltf'),
                  r5c4: new GLTFShape('models/c1/c1_r5c4.gltf'),
                  r5c5: new GLTFShape('models/c1/c1_r5c5.gltf'),
                  r5c6: new GLTFShape('models/c1/c1_r5c6.gltf'),
                  r5c7: new GLTFShape('models/c1/c1_r5c7.gltf'),
                  r5c8: new GLTFShape('models/c1/c1_r5c8.gltf'),
                  r6c1: new GLTFShape('models/c1/c1_r6c1.gltf'),
                  r6c2: new GLTFShape('models/c1/c1_r6c2.gltf'),
                  r6c3: new GLTFShape('models/c1/c1_r6c3.gltf'),
                  r6c4: new GLTFShape('models/c1/c1_r6c4.gltf'),
                  r6c5: new GLTFShape('models/c1/c1_r6c5.gltf'),
                  r6c6: new GLTFShape('models/c1/c1_r6c6.gltf'),
                  r6c7: new GLTFShape('models/c1/c1_r6c7.gltf'),
                  r6c8: new GLTFShape('models/c1/c1_r6c8.gltf'),
                  r6c9: new GLTFShape('models/c1/c1_r6c9.gltf'),
                  r6c10: new GLTFShape('models/c1/c1_r6c10.gltf')
                  },
            colour_2:  
                {
                  r1c1: new GLTFShape('models/c2/c2_r1c1.glb'),
                  r1c2: new GLTFShape('models/c2/c2_r1c2.glb'),
                  r1c3: new GLTFShape('models/c2/c2_r1c3.gltf'),
                  r1c4: new GLTFShape('models/c2/c2_r1c4.gltf'),
                  r1c5: new GLTFShape('models/c2/c2_r1c5.gltf'),
                  r1c6: new GLTFShape('models/c2/c2_r1c6.gltf'),
                  r2c1: new GLTFShape('models/c2/c2_r2c1.gltf'),
                  r2c2: new GLTFShape('models/c2/c2_r2c2.gltf'),
                  r2c3: new GLTFShape('models/c2/c2_r2c3.gltf'),
                  r2c4: new GLTFShape('models/c2/c2_r2c4.gltf'),
                  r2c5: new GLTFShape('models/c2/c2_r2c5.gltf'),
                  r2c6: new GLTFShape('models/c2/c2_r2c6.gltf'),
                  r2c7: new GLTFShape('models/c2/c2_r2c7.gltf'),
                  r3c1: new GLTFShape('models/c2/c2_r3c1.gltf'),
                  r3c2: new GLTFShape('models/c2/c2_r3c2.gltf'),
                  r3c3: new GLTFShape('models/c2/c2_r3c3.gltf'),
                  r3c4: new GLTFShape('models/c2/c2_r3c4.gltf'),
                  r3c5: new GLTFShape('models/c2/c2_r3c5.gltf'),
                  r3c6: new GLTFShape('models/c2/c2_r3c6.gltf'),
                  r3c7: new GLTFShape('models/c2/c2_r3c7.gltf'),
                  r3c8: new GLTFShape('models/c2/c2_r3c8.gltf'),
                  r4c1: new GLTFShape('models/c2/c2_r4c1.gltf'),
                  r4c2: new GLTFShape('models/c2/c2_r4c2.gltf'),
                  r4c3: new GLTFShape('models/c2/c2_r4c3.gltf'),
                  r4c4: new GLTFShape('models/c2/c2_r4c4.gltf'),
                  r5c1: new GLTFShape('models/c2/c2_r5c1.gltf'),
                  r5c2: new GLTFShape('models/c2/c2_r5c2.gltf'),
                  r5c3: new GLTFShape('models/c2/c2_r5c3.gltf'),
                  r5c4: new GLTFShape('models/c2/c2_r5c4.gltf'),
                  r5c5: new GLTFShape('models/c2/c2_r5c5.gltf'),
                  r5c6: new GLTFShape('models/c2/c2_r5c6.gltf'),
                  r5c7: new GLTFShape('models/c2/c2_r5c7.gltf'),
                  r5c8: new GLTFShape('models/c2/c2_r5c8.gltf'),
                  r6c1: new GLTFShape('models/c2/c2_r6c1.gltf'),
                  r6c2: new GLTFShape('models/c2/c2_r6c2.gltf'),
                  r6c3: new GLTFShape('models/c2/c2_r6c3.gltf'),
                  r6c4: new GLTFShape('models/c2/c2_r6c4.gltf'),
                  r6c5: new GLTFShape('models/c2/c2_r6c5.gltf'),
                  r6c6: new GLTFShape('models/c2/c2_r6c6.gltf'),
                  r6c7: new GLTFShape('models/c2/c2_r6c7.gltf'),
                  r6c8: new GLTFShape('models/c2/c2_r6c8.gltf'),
                  r6c9: new GLTFShape('models/c2/c2_r6c9.gltf'),
                  r6c10: new GLTFShape('models/c2/c2_r6c10.gltf'),
                },
            colour_3:
                {
                  r1c1: new GLTFShape('models/glass01/g1_r1c1.glb'),
                  r1c2: new GLTFShape('models/glass01/g1_r1c2.glb'),
                  r1c3: new GLTFShape('models/glass01/g1_r1c3.glb'),
                  r1c4: new GLTFShape('models/glass01/g1_r1c4.glb'),
                  r1c5: new GLTFShape('models/glass01/g1_r1c5.glb'),
                  r1c6: new GLTFShape('models/glass01/g1_r1c6.glb'),
                  r2c1: new GLTFShape('models/glass01/g1_r2c1.glb'),
                  r2c2: new GLTFShape('models/glass01/g1_r2c2.glb'),
                  r2c3: new GLTFShape('models/glass01/g1_r2c3.glb'),
                  r2c4: new GLTFShape('models/glass01/g1_r2c4.glb'),
                  r2c5: new GLTFShape('models/glass01/g1_r2c5.glb'),
                  r2c6: new GLTFShape('models/glass01/g1_r2c6.glb'),
                  r2c7: new GLTFShape('models/glass01/g1_r2c7.glb'),
                  r3c1: new GLTFShape('models/glass01/g1_r3c1.glb'),
                  r3c2: new GLTFShape('models/glass01/g1_r3c2.glb'),
                  r3c3: new GLTFShape('models/glass01/g1_r3c3.glb'),
                  r3c4: new GLTFShape('models/glass01/g1_r3c4.glb'),
                  r3c5: new GLTFShape('models/glass01/g1_r3c5.glb'),
                  r3c6: new GLTFShape('models/glass01/g1_r3c6.glb'),
                  r3c7: new GLTFShape('models/glass01/g1_r3c7.glb'),
                  r3c8: new GLTFShape('models/glass01/g1_r3c8.glb'),
                  r4c1: new GLTFShape('models/glass01/g1_r4c1.glb'),
                  r4c2: new GLTFShape('models/glass01/g1_r4c2.glb'),
                  r4c3: new GLTFShape('models/glass01/g1_r4c3.glb'),
                  r4c4: new GLTFShape('models/glass01/g1_r4c4.glb'),
                  r5c1: new GLTFShape('models/glass01/g1_r5c1.glb'),
                  r5c2: new GLTFShape('models/glass01/g1_r5c2.glb'),
                  r5c3: new GLTFShape('models/glass01/g1_r5c3.glb'),
                  r5c4: new GLTFShape('models/glass01/g1_r5c4.glb'),
                  r5c5: new GLTFShape('models/glass01/g1_r5c5.glb'),
                  r5c6: new GLTFShape('models/glass01/g1_r5c6.glb'),
                  r5c7: new GLTFShape('models/glass01/g1_r5c7.glb'),
                  r5c8: new GLTFShape('models/glass01/g1_r5c8.glb'),
                  r6c1: new GLTFShape('models/glass01/g1_r6c1.glb'),
                  r6c2: new GLTFShape('models/glass01/g1_r6c2.glb'),
                  r6c3: new GLTFShape('models/glass01/g1_r6c3.glb'),
                  r6c4: new GLTFShape('models/glass01/g1_r6c4.glb'),
                  r6c5: new GLTFShape('models/glass01/g1_r6c5.glb'),
                  r6c6: new GLTFShape('models/glass01/g1_r6c6.glb'),
                  r6c7: new GLTFShape('models/glass01/g1_r6c7.glb'),
                  r6c8: new GLTFShape('models/glass01/g1_r6c8.glb'),
                  r6c9: new GLTFShape('models/glass01/g1_r6c9.glb'),
                  r6c10: new GLTFShape('models/glass01/g1_r6c10.glb')  
                }
          }
        },
    icons: {
      add: new Texture('images/addIcon.png'),
      subtract: new Texture('images/subtractIcon.png'),
      eyeDrop: new Texture('images/eyeDropIcon.png'),
      swap: new Texture('images/swap.png'),
      yrotate: new Texture('images/y_ui_icon.png'),
      xrotate: new Texture('images/x_ui_icon.png'),
      zrotate: new Texture('images/z_ui_icon.png'),
      uiEditSelector: new Texture('images/uiEditSelector.png'),
      foundationAdd: new Texture('images/foundationAdd.png',{samplingMode:0})
    },
    images: {
      colourMap: new Texture('images/MiniTown_TX.png',{samplingMode:0}),
      anchorUI: new Texture('images/anchorUITest.png'), 
      floor: new Texture('images/newHQFloor.png'), 
      pgHeader: new Texture('images/pgHeader.png'), 
      pgLogo: new Texture('images/pgLogo.png'), 
      uiOnOff: new Texture('images/uiOnOff.png'),
      uiMenuOn: new Texture('images/uiMenuOn.png'),
      uiMenuOff: new Texture('images/uiMenuOff.png'),
      uiMenuBackground: new Texture('images/uiMenuBackground.png'),
      uiModelBackground: new Texture('images/uiModelBackground.png'),
      uiColourMenu: new Texture('images/uiColourMenu.png'),
      uiClose: new Texture('images/uiClose.png'),
      uiEdit: new Texture('images/uiEdit.png'),
      uiModelBody: new Texture('images/uiModelBody.png'),
      uiModelFace: new Texture('images/uiModelFace.png'),
      uiModelBorder: new Texture('images/uiModelBorder.png'),
      colours: new Texture('images/blockColours.png',{samplingMode:0}), 
      black: new Texture('images/black.png',{samplingMode:0}), 
      grey: new Texture('images/grey.png',{samplingMode:0}), 
      lightGrey: new Texture('images/lightGrey.png',{samplingMode:0}), 
      white: new Texture('images/white.png',{samplingMode:0}), 
      blue: new Texture('images/blue.png',{samplingMode:0}), 
      yellow: new Texture('images/yellow.png',{samplingMode:0}), 
      brown: new Texture('images/brown.png',{samplingMode:0}), 
      orange: new Texture('images/orange.png',{samplingMode:0}), 
      pink: new Texture('images/pink.png',{samplingMode:0}), 
      red: new Texture('images/red.png',{samplingMode:0}), 
      green: new Texture('images/green.png',{samplingMode:0}),
      noSelection: new Texture('images/noSelection.png'),
      saveIcon: new Texture('images/save.png',{samplingMode:0}),
      col1_icon: new Texture('images/col1_icon.png',{samplingMode:0}),
      col2_icon: new Texture('images/col2_icon.png',{samplingMode:0}),
      col3_icon: new Texture('images/col3_icon.png',{samplingMode:0}),
      addImage: new Texture('images/addSelector.png',{samplingMode:0}),
      subtractImage: new Texture('images/subtractSelector.png',{samplingMode:0}),
      eyeImage: new Texture('images/eyeSelector.png',{samplingMode:0}),
      yrotate: new Texture('images/yRotate.png',{samplingMode:0}),
      xrotate: new Texture('images/xRotate.png',{samplingMode:0}),
      zrotate: new Texture('images/zRotate.png',{samplingMode:0}),
      foundationIcon: new Texture('images/foundationIcon.png',{samplingMode:0}),
      r1c1: new Texture('images/r1c1.png'),
      r1c2: new Texture('images/r1c2.png',{samplingMode:0}),
      r1c3: new Texture('images/r1c3.png',{samplingMode:0}),
      r1c4: new Texture('images/r1c4.png',{samplingMode:0}),
      r1c5: new Texture('images/r1c5.png',{samplingMode:0}),
      r1c6: new Texture('images/r1c6.png',{samplingMode:0}),
      r2c1: new Texture('images/r2c1.png',{samplingMode:0}),
      r2c2: new Texture('images/r2c2.png',{samplingMode:0}),
      r2c3: new Texture('images/r2c3.png',{samplingMode:0}),
      r2c4: new Texture('images/r2c4.png',{samplingMode:0}),
      r2c5: new Texture('images/r2c5.png',{samplingMode:0}),
      r2c6: new Texture('images/r2c6.png',{samplingMode:0}),
      r2c7: new Texture('images/r2c7.png',{samplingMode:0}),
      r3c1: new Texture('images/r3c1.png',{samplingMode:0}),
      r3c2: new Texture('images/r3c2.png',{samplingMode:0}),
      r3c3: new Texture('images/r3c3.png',{samplingMode:0}),
      r3c4: new Texture('images/r3c4.png',{samplingMode:0}),
      r3c5: new Texture('images/r3c5.png',{samplingMode:0}),
      r3c6: new Texture('images/r3c6.png',{samplingMode:0}),
      r3c7: new Texture('images/r3c7.png',{samplingMode:0}),
      r3c8: new Texture('images/r3c8.png',{samplingMode:0}),
      r4c1: new Texture('images/r4c1.png',{samplingMode:0}),
      r4c2: new Texture('images/r4c2.png',{samplingMode:0}),
      r4c3: new Texture('images/r4c3.png',{samplingMode:0}),
      r4c4: new Texture('images/r4c4.png',{samplingMode:0}),
      r5c1: new Texture('images/r5c1.png',{samplingMode:0}),
      r5c2: new Texture('images/r5c2.png',{samplingMode:0}),
      r5c3: new Texture('images/r5c3.png',{samplingMode:0}),
      r5c4: new Texture('images/r5c4.png',{samplingMode:0}),
      r5c5: new Texture('images/r5c5.png',{samplingMode:0}),
      r5c6: new Texture('images/r5c6.png',{samplingMode:0}),
      r5c7: new Texture('images/r5c7.png',{samplingMode:0}),
      r5c8: new Texture('images/r5c8.png',{samplingMode:0}),
      r6c1: new Texture('images/r6c1.png',{samplingMode:0}),
      r6c2: new Texture('images/r6c2.png',{samplingMode:0}),
      r6c3: new Texture('images/r6c3.png',{samplingMode:0}),
      r6c4: new Texture('images/r6c4.png',{samplingMode:0}),
      r6c5: new Texture('images/r6c5.png',{samplingMode:0}),
      r6c6: new Texture('images/r6c6.png',{samplingMode:0}),
      r6c7: new Texture('images/r6c7.png',{samplingMode:0}),
      r6c8: new Texture('images/r6c8.png',{samplingMode:0}),
      r6c9: new Texture('images/r6c9.png',{samplingMode:0}),
      r6c10: new Texture('images/r6c10.png',{samplingMode:0})
    },
    blockIconAttribues: {
        iconr1c1: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 17,sourceTop: 17},
        iconr1c2: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 288,sourceTop: 20},
        iconr1c3: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 566,sourceTop: 19},
        iconr1c4: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 845,sourceTop: 25},
        iconr1c5: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1124,sourceTop: 25},
        iconr1c6: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1400,sourceTop: 28},
        iconr2c1: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 47,sourceTop: 273},
        iconr2c2: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 326,sourceTop: 272},
        iconr2c3: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 601,sourceTop: 277},
        iconr2c4: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 881,sourceTop: 275},
        iconr2c5: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1155,sourceTop: 278},
        iconr2c6: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1435,sourceTop: 282},
        iconr2c7: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1711,sourceTop: 284},
        iconr3c1: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 80,sourceTop: 526},
        iconr3c2: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 360,sourceTop: 529},
        iconr3c3: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 630,sourceTop: 526},
        iconr3c4: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 910,sourceTop: 530},
        iconr3c5: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1189,sourceTop: 530},
        iconr3c6: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1464,sourceTop: 536},
        iconr3c7: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1742,sourceTop: 536},
        iconr3c8: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 2023,sourceTop: 538},
        iconr4c1: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 115,sourceTop: 15},
        iconr4c2: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 392,sourceTop: 780},
        iconr4c3: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 668,sourceTop: 783},
        iconr4c4: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 944,sourceTop: 782},
        iconr5c1: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 150,sourceTop: 1032},
        iconr5c2: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 425,sourceTop: 1035},
        iconr5c3: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 702,sourceTop: 1038},
        iconr5c4: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 981,sourceTop: 1039},
        iconr5c5: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1260,sourceTop: 1038},
        iconr5c6: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1536,sourceTop: 1041},
        iconr5c7: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1812,sourceTop: 1042},
        iconr5c8: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 2089,sourceTop: 1045},
        iconr6c1: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 185,sourceTop: 1286},
        iconr6c2: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 459,sourceTop: 1288},
        iconr6c3: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 738,sourceTop: 1289},
        iconr6c4: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1015,sourceTop: 1290},
        iconr6c5: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1292,sourceTop: 1293},
        iconr6c6: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1572,sourceTop: 1295},
        iconr6c7: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 1845,sourceTop: 1298},
        iconr6c8: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 2127,sourceTop: 1298},
        iconr6c9: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 2401,sourceTop: 1298},
        iconr6c10: {sourceWidth: 200,sourceHeight: 200,sourceLeft: 2670,sourceTop: 1304}
      },
      colourBlockAttribues: {
        col1: {sourceWidth: 512,sourceHeight: 512,sourceLeft: 155,sourceTop: 484},
        col2: {sourceWidth: 512,sourceHeight: 512,sourceLeft: 288,sourceTop: 20}
      }
}
